insert into productionRoles values (production_id_seq.nextval, 'composer');
insert into productionRoles values (production_id_seq.nextval, 'remixer');
insert into productionRoles values (production_id_seq.nextval, 'recording engineer');
insert into productionRoles values (production_id_seq.nextval, 'producer');
insert into productionRoles values (production_id_seq.nextval, 'co-producer');
insert into productionRoles values (production_id_seq.nextval, 'accompanist');
insert into productionRoles values (production_id_seq.nextval, 'arranger');
insert into productionRoles values (production_id_seq.nextval, 'audio engineer');
insert into productionRoles values (production_id_seq.nextval, 'vocalist');
insert into productionRoles values (production_id_seq.nextval, 'backing singer');
insert into productionRoles values (production_id_seq.nextval, 'conductor');
insert into productionRoles values (production_id_seq.nextval, 'mixer');
insert into productionRoles values (production_id_seq.nextval, 'mastering engineer');
insert into productionRoles values (production_id_seq.nextval, 'sound designer');
insert into productionRoles values (production_id_seq.nextval, 'performer');
insert into productionRoles values (production_id_seq.nextval, 'writter');
insert into productionRoles values (production_id_seq.nextval, 'lyricist');
commit;
select * from productionRoles
fetch FIRST 5 ROWS ONLY;